import { Nunito } from "next/font/google";
import "./globals.css";
import PlausibleProvider from 'next-plausible'


const nunito = Nunito({ subsets: ["latin"] });

export const metadataF = {
  title: "Get Global",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <PlausibleProvider domain="getglobal.pro"
          // trackLocalhost={true}
          // enabled={true}
          taggedEvents={true}
        />
      </head>
      <body className={nunito.className}>{children}</body>
    </html>
  );
}
